version: '3.8'

services:
  app:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - mailpit
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit  # Atualiza a imagem para a correta
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Interface Web (onde você verá os e-mails)
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
